image: maven:3.8.1-jdk-11

stages:
  - build
  - test

variables:
  MAVEN_CLI_OPTS: "-s settings.xml"
  MAVEN_OPTS: "-Dmaven.repo.local=FlightBookingSystem/"

cache:
  key: "${CI_JOB_NAME}-${CI_COMMIT_REF_SLUG}"
  paths:
    - FlightBookingSystem/

build:
  stage: build
  script:
    - mvn clean -f path/to/pom.xml

test:
  stage: test
  script:
    - mvn test -f path/to/pom.xml
